name: project_7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_image_stack: ^0.0.7
  pinput: ^5.0.0
  dio: ^5.7.0
  url_launcher: ^6.3.0
  intl: ^0.19.0
  device_preview: ^1.2.0
  loading_animation_widget: ^1.2.1
  panara_dialogs: ^0.1.5
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  flutter_image_slideshow: ^0.1.6
  flutter_rating_bar: ^4.0.1
  calendar_date_picker2: ^1.1.7
  shared_preferences: ^2.3.2
  
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
      - assets/
      - assets/icons/
      - assets/images/
      - .env
