name: project7
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_rating_stars: ^1.1.0
  get_it: ^7.7.0
  get_storage: ^2.1.1
  grouped_list: ^6.0.0
  image_picker: ^1.1.2
  pinput: ^5.0.0
  dio: ^5.7.0
  bloc: ^8.1.4
  meta: ^1.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - 'assets/'
  - 'assets/images/'
  # - 'assets/fonts/'

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf