import 'package:dio/dio.dart';
import 'package:project_judge/network/constant_network.dart';

mixin CreateProjecttMethod on ConstantNetwork {
  Future<void> createProject(
      {required String token,
      required String userID,
      required String date,
      required String edit}) async {
    try {
      final respose = await dio.post(
          "https://tuwaiq-gallery.onrender.com/v1/supervisor/create/project",
          data: {"user_id": userID, "time_end_edit": date, "edit": edit},
          options: Options(headers: {
            "Authorization":
                "Bearer YWU1YzhkZmU4MWI3NWE1Y2Y3MzQ0ZjQwNTg2NmQwOWI4MWUwZTExZjQyNDNlNTI1YzRiNDAzMDBiZDE0YWQ0MTIxMTBmNGNhYjgyZjIwZDU4NmYyMjllNmY0MmY2ZTE1ZDEzODAwNTQ3ODc0MzQ0YjU4MTNmNDljZGU1NmYyMjE1NDk3NjdhNzYyN2UxZWMzYjQ0NGZhZDZhMzA0OTY4M2QwMDYyYmEzZjAzMzU5OWIyMDNjODVjZDQyYTRiYjk4YjU2NzYxZDFlYmVkNzExZGU4ZjAyNGE1NjAxMTg2ZjE0Yjc1MjIwNGM0MDdkYmNmZTc2NWJlYzY4MDU0ZjAzYmNmZGY3NWM1ZDgxZGYwZWE1ZDllOTc1MDIxMTVhNWI4YjU5ODAyMTM0MTc2NmRjYjA3ZjE4ZDZlMmRlM2M0ZThjODc3OTFjNGMyOTUwYjE5MmVjMzJlMTZkN2JiNDRhNWI3NzU0MDIyYTdmODk3MzE3NWQ1MzM5NTUzODNhYmExZGY1MzE5OTY0YWYwYjc0MmMxZThmNTI4YmZiODNlMTE1OTE3ZTZjYjMyMWQ2NmJlNDA5YTA2Y2RmYTFkZWRhNzE5ZTU2MTFlMGIyN2NjMDE1MjI5ZmM1ZGVkYTgxMjViZDNjZmVmM2M4MDg5NjA4OWJlMGE0M2NjY2E2MDc0ZmYyZTQ5MDVhM2RmMDI2ZDU4NDhiNDhmYzBkYjY1MGFlMGY3NzFiZTlkOWU4OGQ0ZDk5YzNkODkxNWNjMGRhNzdlOGZiNWY1NzNlMGFkNWU1N2U0MWZjODQ0MzhjYWJmZThlZGVkYWI1ODQ2OTIzNzE4MDFhZWZmZGRkZTkzMmVlN2FmMTgzMjA0ZmMxZDMxMmMzYWU5YzRkNGZhOGMwMzg4NmI4NDU3ODg5YjlhMGM1Zjk4YWU0N2EwNjVhYTcwMmU1OGI4NmRiNTk1ODRjNzM5MjBkODY2MGRiYzRkNjk4MjA3OGMwYWIxNjA0NzgzOTk4NTE3NmFkYjE2ZGRiZjdlNTMwOGVhYmM3ODc3YmI2YWIxMTQzMjczMzBjMjljZmU1OTc5ZDMzYzViN2IzZmI0YzMxZjQ1ZjhiMDZmZDVjMTczZjQzN2RlZjM1MGE0NmY1OTc0NjFjNTY3MmZjOWI1ZmQ0OTRhNjUyMmQyZWY0YmE0NDM5YzA2NDRmMzA0YWEzODk1ZDQyYWUzOWRiMTVlNjBjYWZmODkzNjRjZjI3MTMzMzI4ZTIwNWU1OTc4YmNkODJkMGVlMzVlODc4OTg4OTg5OWI5ZmVjZjRiNzZiZGE3NmMzNTBlOWM2ZDJiODgwNThkNWYwYjZiMmQzY2YxMTJkYjY2YzQwMTE0YWU5YmM1NmU4ODZiN2UzNTc1NjE4ZWZlMjQ0YmY2ZTFmMTc4ZmY2ODI5MTljNjk5YzNmOGM2ZTI4NDM4NzkzNmRlNTk2YzUxMDk3ODE4MGIzYTY2OTk5OWE0Y2JjZGZjODg1ZTU5ZTU0NTU4YjllNzhhZmM5OTNlZjA5NWQ5MTA5OTUwZGNlMzk5ZjgwZGVmYzRjNDlkMDE4YWQ1ODM3YTc0N2QyOWJiMTZiNDEyN2M5ZDY1NGYzMDRmMWU1OWI2YzhlYzUyNTYyZTA1MjkxMmJiM2RjZjM3NmI1MzYwNDcxZDc0NDMzNDJlMDUyNDVmYWIzMjIzNDZjZmQ2NmJmNjFlY2E0YzVkM2I0NThjYTU0ZjdkZWIxODc2MjkxMDY5MGU1YTQwMGY3NmVmYzAzNzY4NmZhYjc1MDY2NTNiMmJhNzQ1NGE0OGU3ZTFiZDg5NWE3ZDVkOTk2ZTQxNmExMjY0ZjNlMTA0N2Y5ZGM2ZDA1NmI5ZDM3YzU4YjkwYTA0Zjc0ZmI3MTU5ZTM4Nzk1ZDBkOTRlZDRlMGM4YTc4ZjI2MjA4YTQ1YjY1MTE4YWRjNWY0YWM2NDhmNWQ4YjI2YzI0OTFiNmJkZTE3N2U3ZWJlMzc0ZDBkMTMxODEzZGJkY2QwMWZjYzc1NzQ2ODlhNWI1ZGYyZTE1NWZkNDc4N2MxODRjYzA1Mjg4ZWU0OTdhMTFkMmU4MjEwMjhjZDBlZjBiZGI0MDUxNThmYjdmODc3Yjk0OTBlZTVkNjViZjUyMzhjYWY4YjZiMjk4YzIyY2M2ZDEzYTRmNzYzNzRhYmExYjVkZTJiZTIwYTNjODI3M2I4MzZiZjc0ODJmMTkxZDU2NWQ3ODJiZWZlYTQ5OGU5MTY1ZDZkZTY1"
          }));
     // return(respose.data['data']['project_id']);
    } on DioException catch (e) {
      throw FormatException(e.response?.data['data']);
    } catch (e) {
      throw FormatException("unkown error $e");
    }
  }
}
